### ISSUE TITLE
Portability issues when using custom directories

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nsc#110]
Currently `nsc` when using a pair of custom directories via environment variables such as: 

```
export NKEYS_PATH=$(pwd)/nkeys
export NSC_HOME=$(pwd)/accounts
```

It generates metadata that uses the absolute path so it cannot be committed into the version control. Workaround for now is to add them to `.gitignore`. For example:

```
 cat .gitignore 
accounts/nsc.json
accounts/nats/O/.nsc
```

**Comment by wallyqs** [comment]
Actually after trying this now getting: 

```
nsc list operators
no operators defined - init an environment
```

**Comment by aricart** [comment]
Currently, $NSC_HOME is not a per project directory but the home for the cli, so content for the 'stores' is $NSC_HOME/nats. Perhaps $NSC_DATA should be the environment variable for where the content goes. WDYT?

**Comment by wallyqs** [comment]
Current workaround is to look for the the `./accounts/nsc.json` file and modify it absolute path with the new folder:

```
{"store_root":"/Users/wallyqs/.../nsc/accounts/nats"}
```

**Comment by sasbury** [comment]
do you want the store root to move all the time? I suspect that is dangerous. I use $NSC_HOME to manage multiple installs, it is much safer.

i don't like the idea of $NSC_DATA, seems like an indirection on an indirection

**Comment by wallyqs** [comment]
Need to be able to do this flow:

```
git clone https://.../my-repo
cd my-repo
tree nsc/ <--- root with jwts
export NSC_HOME=$(pwd)/nsc/accounts
```

Then be able to use `nsc list` for example

**Comment by aricart** [comment]
`nsc env -s /path/to/directory/containing/operators` manages the location of the JWT files. $NKEYS_PATH sets the keyring to use.
