### ISSUE TITLE
Error: unable to validate expected prefixes - [account] when creating user

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nsc#112]
When trying to create user for an account get the following error:

```
nsc add user -a A... -n foo
Error: unable to validate expected prefixes - [account]
```

**Comment by wallyqs** [comment]
Seems that the error is that what this generates is expecting an account prefix but a user prefix is the result:

```
nsc add user -n eu-user-a
---  UDWGK...
--- PREFIXES [account]
```

**Comment by aricart** [comment]
-a is an account name, not an nkey
nsc add account -n A
nsc add account -n B
nsc add user -n U -a A
