### ISSUE TITLE
nsc list keys

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nsc#16]
Might be helpful.

**Comment by aricart** [comment]
@derekcollison what do you mean - you mean show the public keys or show if we have a signing nkey

or do we just want to dump all the keys we have?

**Comment by derekcollison** [comment]
If I do have signing keys available, be good to be able to name them and easily chose one to sign things versus -K option.

**Comment by aricart** [comment]
This would be like naming an entry that lives else where so the keystore can find it?

**Comment by derekcollison** [comment]
Was mostly thinking about having signing keys and allowing me to pick which signing key I wanted to use.

**Comment by aricart** [comment]
Current commands on interactive, if you have more than one key associated allow you to pick interactively:

```
nsc add account -i
? account name A
? generate an account nkey Yes
? valid 0
? valid until (0 is always) 0
? select the key to sign the account  [Use arrows to move, type to filter]
> OAYIKPPTZGXWZDCQZJ4NTN6HN2DX4MA6OBSM54MWLLPFG54PIULSL6NP
  OC4RKFJI2VTIOCPOEEG34FUIE6ONOZZBYGIB2AZ7O5UV4ES6MSD752PV
```
you can also add keys, and use them for signing:
`nsc generate nkey --account --store`

and list the ones that are not referenced in the current o/a/u context:
`nsc list keys --all --not-referenced`
