### ISSUE TITLE
init doesn't save keys correctly and prints a weird message

### ISSUE THREAD

**Issue by sasbury** [nats-io/nsc#160]
% nsc init -u http://localhost:6060/jwt/v1/operator -n First
Error: init failed: account update succeeded
NGS created a new free billing account for your JWT, First [ADVMWKLXBKPE]. Use the ngs command to manage your billing plan.''

nsc folder is correct:

 % tree ~/.test_nsc
/Users/sasbury/.test_nsc
├── nats
│   └── synadia
│       ├── accounts
│       │   └── First
│       │       └── First.jwt
│       └── synadia.jwt
└── nsc.json

but the nkey folder is empty.

 % nsc env
╭───────────────────────────────────────────────╮
│                NSC Environment                │
├──────────────────┬─────┬──────────────────────┤
│ Setting          │ Set │ Effective Value      │
├──────────────────┼─────┼──────────────────────┤
│ $NKEYS_PATH      │ Yes │ ~/.test_nkeys        │
│ $NSC_HOME        │ Yes │ ~/.test_nsc          │
│ Config           │     │ ~/.test_nsc/nsc.json │
├──────────────────┼─────┼──────────────────────┤
│ Stores Dir       │     │ ~/.test_nsc/nats     │
│ Default Operator │     │ synadia              │
│ Default Account  │     │ First                │
╰──────────────────┴─────┴──────────────────────╯

**Comment by sasbury** [comment]
Note - nsc init -n O - works, somethign with the -u maybe

**Comment by sasbury** [comment]
The issue is that the NGS server returns a message which store claim treats as an error so the CreateAccount call in init exits before saving the NKey

**Comment by aricart** [comment]
Fixed by #162
