### ISSUE TITLE
multiple inits overwrites account

### ISSUE THREAD

**Issue by sasbury** [nats-io/nsc#163]
From nsc folder ...

% go run main.go init -u http://localhost:6060/jwt/v1/operator         
Successfully pushed the account configuration to the remote server.
Please review the following operator message:
NGS created a new free billing account for your JWT, Test [ADIVLXEVQKUB]. Use the ngs command to manage your billing plan.
The account configuration was successfully pulled from the operator.
The operator may have set some limits or added imports to your account.
Please enter nsc describe account to review your account configuration.

Success!! created an account and user named "Test" under managed operator "synadia".
User creds file stored in "/Users/sasbury/.test_nkeys/creds/synadia/Test/Test.creds"
sasbury@synadiaIMac ~/Dropbox/synadia/code/nsc 
 % go run main.go init -u http://localhost:6060/jwt/v1/operator
Successfully pushed the account configuration to the remote server.
Please review the following operator message:
NGS created a new free billing account for your JWT, Test [ADMOFBQG76X7]. Use the ngs command to manage your billing plan.
The account configuration was successfully pulled from the operator.
The operator may have set some limits or added imports to your account.
Please enter nsc describe account to review your account configuration.

Success!! created an account and user named "Test" under managed operator "synadia".
User creds file stored in "/Users/sasbury/.test_nkeys/creds/synadia/Test/Test.creds"
sasbury@synadiaIMac ~/Dropbox/synadia/code/nsc 
 % go run main.go init -u http://localhost:6060/jwt/v1/operator
Successfully pushed the account configuration to the remote server.
Please review the following operator message:
NGS created a new free billing account for your JWT, Test [ACYXNELHMWYF]. Use the ngs command to manage your billing plan.
The account configuration was successfully pulled from the operator.
The operator may have set some limits or added imports to your account.
Please enter nsc describe account to review your account configuration.

Success!! created an account and user named "Test" under managed operator "synadia".
User creds file stored in "/Users/sasbury/.test_nkeys/creds/synadia/Test/Test.creds"

**Comment by aricart** [comment]
FIXED #193
