### ISSUE TITLE
Help on expiry confused me

### ISSUE THREAD

**Issue by sasbury** [nats-io/nsc#185]
Not sure of the solution, i like that we can do `--expiry 1d` but i couldn't figure that out from the help. Had to look at tests to figure it out.

**Comment by aricart** [comment]
the help told you       
`--expiry string       valid until ('0' is always) - yyyy-mm-dd, #m(inutes), #h(ours), #d(ays), #w(eeks), #M(onths), #y(ears) (default "0")`

**Comment by sasbury** [comment]
It said something but i wasn't sure if that was a formatting message so I could do yyyy or hh:mm or something. I wanted a small example because it opened my eyes to the meaning of the existing message
