### ISSUE TITLE
default prefix is confusing on create stream import from token

### ISSUE THREAD

**Issue by sasbury** [nats-io/nsc#210]
The default "prefix"/"local" is the subject, should probably just be blank if i don't want to set it

Not sure how this works for services

**Comment by aricart** [comment]
for services it is required, can be the same as the source of the subject.
```
➜ nsc add operator O
[ OK ] generated and stored operator key "OBYW3CQW4WMUOYPPQVO7QKSORGIDV3GAD54KOKF4CG5WS6N7UQZKJQBX"
[ OK ] added operator "O"

~
➜ nsc add account A
[ OK ] generated and stored account key "ACEYCCCVWIBD7OACND34OBLTLFQPLLTJYMRF5Y734FJPZ6O35EVE4FZA"
[ OK ] added account "A"

~
➜ nsc add export -i
? export type stream
? subject foo
? name foo
? private stream No
[ OK ] added public stream export "foo"

~ 5s
➜ nsc add account B
[ OK ] generated and stored account key "AA7XV5VPVOFKR3ZIDHZOV5I3LOAUTA2VV5GENB5XANDMTUZJRGB35R4P"
[ OK ] added account "B"

~
➜ nsc add import -i
? select account B
? pick from locally available exports Yes
? select the export   -> foo
? name foo
? stream prefix subject
[ OK ] added stream import "foo"

~ 7s
➜ nsc add export -i
? select account A
? export type service
? subject q
? name q
? private service No
? track service latency No
[ OK ] added public service export "q"

~ 8s
➜ nsc add import -i
? select account B
? pick from locally available exports Yes
? select the export   <- q
? name q
? local subject q
[ OK ] added service import "q"

~ 6s
```

**Comment by aricart** [comment]
If this is not what you are seeing, reopen.

**Comment by sasbury** [comment]
none of those are adding from a token on the command line, this is if you pass the token on the command line as a flag.

**Comment by aricart** [comment]
```
➜ nsc add export -i
? select account A
? export type stream
? subject priv_stream
? name priv_stream
? private stream Yes
[ OK ] added private stream export "priv_stream"

~ 9s
➜ nsc add export -i
? select account A
? export type service
? subject pq
? name pq
? private service Yes
? track service latency No
[ OK ] added private service export "pq"

~ 9s
➜ nsc add import -i
? select account B
? pick from locally available exports Yes
? select the export   -> priv_stream [!]
? name priv_stream
? stream prefix subject
[ OK ] added stream import "priv_stream"

~
➜ nsc add import -i
? select account B
? pick from locally available exports Yes
? select the export   <- pq [!]
? name pq
? local subject pq
[ OK ] added service import "pq"

~ 7s
➜ nsc describe account -i
? select account  [Use arrows to move, type to filter]
  A
> B
Error: interrupt

~
✘1 ➜ nsc describe account B
╭──────────────────────────────────────────────────────────────────────────────────────╮
│                                   Account Details                                    │
├───────────────────────────┬──────────────────────────────────────────────────────────┤
│ Name                      │ B                                                        │
│ Account ID                │ AA7XV5VPVOFKR3ZIDHZOV5I3LOAUTA2VV5GENB5XANDMTUZJRGB35R4P │
│ Issuer ID                 │ OBYW3CQW4WMUOYPPQVO7QKSORGIDV3GAD54KOKF4CG5WS6N7UQZKJQBX │
│ Issued                    │ 2019-09-23 19:03:41 UTC                                  │
│ Expires                   │                                                          │
├───────────────────────────┼──────────────────────────────────────────────────────────┤
│ Max Connections           │ Unlimited                                                │
│ Max Leaf Node Connections │ Unlimited                                                │
│ Max Data                  │ Unlimited                                                │
│ Max Exports               │ Unlimited                                                │
│ Max Imports               │ Unlimited                                                │
│ Max Msg Payload           │ Unlimited                                                │
│ Max Subscriptions         │ Unlimited                                                │
│ Exports Allows Wildcards  │ True                                                     │
├───────────────────────────┼──────────────────────────────────────────────────────────┤
│ Exports                   │ None                                                     │
╰───────────────────────────┴──────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────────────────────────────────────────────╮
│                                       Imports                                        │
├─────────────┬─────────┬─────────────┬──────────────┬─────────┬──────────────┬────────┤
│ Name        │ Type    │ Remote      │ Local/Prefix │ Expires │ From Account │ Public │
├─────────────┼─────────┼─────────────┼──────────────┼─────────┼──────────────┼────────┤
│ foo         │ Stream  │ foo         │              │         │ A            │ Yes    │
│ pq          │ Service │ pq          │ pq           │         │ A            │ No     │
│ priv_stream │ Stream  │ priv_stream │              │         │ A            │ No     │
│ q           │ Service │ q           │ q            │         │ A            │ Yes    │

```

**Comment by aricart** [comment]
The prefix is not defaulted for streams (private or otherwise) - and for streams, defaults to the original subject on the service.

**Comment by sasbury** [comment]
root@0c9b1f8830a5:/home/app# nsc add import -u boom_act.jwt 
[ OK ] push jwt to account server
[ OK ] pull jwt from account server
[ OK ] added stream import "boom"
root@0c9b1f8830a5:/home/app# nsc describe account
╭──────────────────────────────────────────────────────────────────────────────────────╮
│                                   Account Details                                    │
├───────────────────────────┬──────────────────────────────────────────────────────────┤
│ Name                      │ gamma                                                    │
│ Account ID                │ ABJOXOLMLK3USTZMOGAV3VAYD3K2EM6VT56RKJBCFEDS3VRIHYN4NYDL │
│ Issuer ID                 │ OADMJZUZQFEK3QA4BL7RC4C527Y6FSJREEW4PQNGNSCTSZCJGDD7GEYG │
│ Issued                    │ 2019-09-23 20:07:54 UTC                                  │
│ Expires                   │                                                          │
├───────────────────────────┼──────────────────────────────────────────────────────────┤
│ Max Connections           │ 100                                                      │
│ Max Leaf Node Connections │ 2                                                        │
│ Max Data                  │ 25 GB (25000000000 bytes)                                │
│ Max Exports               │ 10                                                       │
│ Max Imports               │ 25                                                       │
│ Max Msg Payload           │ 128 kB (128000 bytes)                                    │
│ Max Subscriptions         │ 500                                                      │
│ Exports Allows Wildcards  │ False                                                    │
├───────────────────────────┼──────────────────────────────────────────────────────────┤
│ Exports                   │ None                                                     │
╰───────────────────────────┴──────────────────────────────────────────────────────────╯

╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                      Imports                                                                                       │
├────────┬─────────┬────────────────────────────────────────────────────────────────────┬──────────────┬─────────┬──────────────────────────────────────────────────────────┬────────┤
│ Name   │ Type    │ Remote                                                             │ Local/Prefix │ Expires │ From Account                                             │ Public │
├────────┼─────────┼────────────────────────────────────────────────────────────────────┼──────────────┼─────────┼──────────────────────────────────────────────────────────┼────────┤
│ boom   │ Stream  │ boom                                                               │ boom         │         │ beta                                                     │ No     │
│ active │ Stream  │ ngs.active                                                         │              │         │ ADMR4WCP5QIUUQUR6IDHPQ4IFSKOW4SQEOK5OI44PYDWF4GRP4OJO5SK │ Yes    │
│ echo   │ Service │                                                                    │ ngs.echo     │         │ ADMR4WCP5QIUUQUR6IDHPQ4IFSKOW4SQEOK5OI44PYDWF4GRP4OJO5SK │ Yes    │
│ usage  │ Service │ ngs.usage.ABJOXOLMLK3USTZMOGAV3VAYD3K2EM6VT56RKJBCFEDS3VRIHYN4NYDL │ ngs.usage    │         │ ADMR4WCP5QIUUQUR6IDHPQ4IFSKOW4SQEOK5OI44PYDWF4GRP4OJO5SK │ No     │
╰────────┴─────────┴────────────────────────────────────────────────────────────────────┴──────────────┴─────────┴──────────────────────────────────────────────────────────┴────────╯
root@0c9b1f8830a5:/home/app#

**Comment by sasbury** [comment]
activation - eyJ0eXAiOiJqd3QiLCJhbGciOiJlZDI1NTE5In0.eyJqdGkiOiI1Q000NURYWFhRWEY3TzJNTEpVN1JZRlRQN0RLQUE0QkM1WloySldaSzZTNFBMWEJEQldBIiwiaWF0IjoxNTY5MjY5MjM3LCJpc3MiOiJBRElZV0RXSVdSUllFR0xPVDU1STNIWEVYN0dGQzdWTlFPNFpOUlU2MlhTT01ER0cyM1hNN1lLSyIsIm5hbWUiOiJib29tIiwic3ViIjoiQUJKT1hPTE1MSzNVU1RaTU9HQVYzVkFZRDNLMkVNNlZUNTZSS0pCQ0ZFRFMzVlJJSFlONE5ZREwiLCJ0eXBlIjoiYWN0aXZhdGlvbiIsIm5hdHMiOnsic3ViamVjdCI6ImJvb20iLCJ0eXBlIjoic3RyZWFtIn19.01mhx2XamcMV_j1KDd1N3WeE53lb3ADl1XhGLDYwrLneEtiSsm0EaZ0yvam8ScfS_5Me32AUzVSCXkLaZy6-BA

**Comment by sasbury** [comment]
Note the local/prefix is "boom" which will be confusing since i imported a stream on "boom" but have to subscribe to "boom.boom"

**Comment by aricart** [comment]
https://github.com/nats-io/nsc/pull/213
