### ISSUE TITLE
Issue with issueraccount in users

### ISSUE THREAD

**Issue by sasbury** [nats-io/nsc#214]
We ran into a user with an issuer account that it shouldn't have had. No idea how this happened, but there are a couple places where issueraccount is set because the context has a different account than the one being used to sign.

These are in entity and edituser.

I suspect the issue is that a flag was used to pick the account but the context defaulted to a different one somehow.

**Comment by sasbury** [comment]
also, it is possible this should get undone sometimes and isn't

**Comment by sasbury** [comment]
might have been that the store was in one place but the user was in another place somehow

**Comment by aricart** [comment]
unable to reproduce.
