### ISSUE TITLE
env account change isn't taking effect for me

### ISSUE THREAD

**Issue by sasbury** [nats-io/nsc#22]
nsc env --account synadia_account                                                               [0]
╭───────────────────────────────────────────────────╮
│                  NSC Environment                  │
├──────────────────┬─────┬──────────────────────────┤
│ Setting          │ Set │ Effective Value          │
├──────────────────┼─────┼──────────────────────────┤
│ $NKEYS_PATH      │ No  │ /Users/sasbury/.nkeys    │
│ $NSC_HOME        │ No  │ /Users/sasbury/.nsc      │
├──────────────────┼─────┼──────────────────────────┤
│ Stores Dir       │     │ /Users/sasbury/.nsc/nats │
│ Default Operator │     │ synadia_operator         │
│ Default Account  │     │ test_account             │
│ Default Cluster  │     │                          │
╰──────────────────┴─────┴──────────────────────────╯

**Comment by aricart** [comment]
This is fixed
