### ISSUE TITLE
make nsc available on homebrew

### ISSUE THREAD

**Issue by aricart** [nats-io/nsc#224]

**Comment by ColinSullivan1** [comment]
You're likely aware, but if it helps we have nats-server and nats-streaming-server formulas here:

https://github.com/Homebrew/homebrew-core/blob/bb08cac540089ac9f30b72e0cbec9b6e3d67b9c2/Formula/nats-server.rb

https://github.com/Homebrew/homebrew-core/blob/f647c1f85209c8686dc295fa9f3327b265ef656c/Formula/nats-streaming-server.rb

**Comment by aricart** [comment]
@ColinSullivan1 who is keeping the formulas up-to-date?
If we use taps, goreleaser can do it all for us, and it also installs our build of the software, not a local build.

**Comment by ColinSullivan1** [comment]
Having goreleaser do it for us would be ideal...

**Comment by aricart** [comment]
Fixed in #245
