### ISSUE TITLE
Flag to disable auto update and metadata

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nsc#240]
Implement option to be able to disable some of the metadata (nsc.json) file, git ignores and auto update that could help when scripting `nsc`.

**Comment by aricart** [comment]
What should the behaviour be? PWD? The git ignores means you are checking in nkeys, but sounds fair, unless you are not expecting that.

**Comment by wallyqs** [comment]
Maybe something like having an `NSC_NO_MAGIC` env var that if true does not generate the nsc.json file and tries to auto update, use case for example having a container and mounting the nkeys and credentials as in nats-box: 

`docker run --rm -it -v $(pwd)/nsc:/nsc synadia/nats-box:latest`
