### ISSUE TITLE
use canonical folders

### ISSUE THREAD

**Issue by gun1x** [nats-io/nsc#249]
nsc is not respecting the folder structure that most distributions use and you get the feeling that is just leaves "stuff" "everywhere".

These folders are currently used:
* installation script pulls binary to `~/.nsccli` and recommends to change `$PATH`
* configuration directory defaults to `~/tmp/nsc`
* nkeys default to `~/.nkeys`

I suggest using these folders instead:
* script should install to `/usr/local/bin/` or `/opt/nats/nsc/` (or maybe put install PKG in [aur](https://aur.archlinux.org/))
* default configuration to `/var/lib/nats/nsc/` or `/etc/nats/nsc` or `~/.config/nats/nsc`
* default nkeys to `/var/lib/nats/nsc/nkeys` or `/etc/nats/nsc/nkeys` or `~/.config/nats/nsc/keys`

Or even more clean:
* run via Docker
* provide documentation on which folders to attach to container

**Comment by gun1x** [comment]
After discussing on Slack, this got pointed to me: https://hub.docker.com/r/synadia/nats-box

However this image does not have any link to the [repo](https://github.com/nats-io/nats-box) behind the image so it just looks not official. I think it should also be mentioned on the main page of the nsc documentation: https://docs.nats.io/nats-tools/nsc

**Comment by wallyqs** [comment]
Thanks for the feedback, I agree. Adding a link to nats-box in the README here for now: https://github.com/nats-io/nsc/pull/250

**Comment by gun1x** [comment]
Also please bump https://hub.docker.com/r/synadia/nats-box to the new version of nsc.

**Comment by wallyqs** [comment]
Version of nats-box bumped as well: https://github.com/nats-io/nats-box/releases/tag/v0.3.0

**Comment by gun1x** [comment]
If you run multiple commands with the docker container, it will take a lot of time to execute. However, you can pack everything in a script and just attach the script to the container, like this:

```bash
#!/bin/bash
nscFolder="$(pwd)/tmp/nsc/"
rm -rf "$nscFolder"
mkdir -p "$nscFolder"
cp nsc_commands.sh "$nscFolder"

docker run --rm \
  -v "${nscFolder}:/nsc/" \
  synadia/nats-box:latest \
  /nsc/nsc_commands.sh
```

This assumes you have your `nsc_commands.sh` file that contains all the commands. Here is a quick example:
```sh
#!/bin/sh
nsc add operator OP
nsc edit operator --service-url nats://0.0.0.0:4222
nsc add account A
nsc add user user1
nsc add account B
nsc add user userFromAccountB
nsc generate config --mem-resolver --config-file "/nsc/nats-server.conf"
```

This being said, I achieved the "clean" experience I was looking for, so that nsc does not leave stuff all over my home folder. From my point of view, the ticket can be closed.

@wallyqs thank you for your help, both here and on Slack. <3
