### ISSUE TITLE
Add a way to get keys from objects for scripting

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nsc#264]
To facilitate scripting we need a way to have `nsc` write the public key of an object (operator, account, user, activation token). 

For example:
```bash
$ nsc print key ./nsc/accounts/nats/KO/accounts/SYS/SYS.jwt
ABQKAY62555JHCLGRBRQSEAVXI5VSTMZIMLYXDYI6WCYZWD4ISEECZ2Y
```

This would allow scripts to direct output to env vars, passed to helm charts, etc, avoiding manual copy-and-paste in setting up system accounts, etc.

**Comment by aricart** [comment]
@ColinSullivan1 wouldn't it be easier to do something like this:
`nsc describe operator --raw | cjwt | jq .iss` 

This would allow scripting to access any field, not some specific field that may fit one case, but not another.

**Comment by aricart** [comment]
I will add the ability to output JSON directly from the tool, this will enable parsing the configuration as JSON from any other tool.

**Comment by ColinSullivan1** [comment]
This would certainly work but requires two additional tools to be installed.  Just printing the account key to stdout would let us do something like:
```
KEY=`nsc print key ./nsc/accounts/nats/KO/accounts/SYS/SYS.jwt`
```
Elsewhere use `$KEY` in the script and even server configuration.

**Comment by aricart** [comment]
I am going to make it so that it outputs json, and then you can use jq to
query anything you want.

**Comment by matthiashanel** [comment]
Hey Alberto, watch out for stdio....
