### ISSUE TITLE
"nsc generate profile"

### ISSUE THREAD

**Issue by aricart** [nats-io/nsc#287]
Given an URL of the form:

`nsc://operator/account/user` resolve a JSON that looks like:

```json
{
  "user_creds": "<filepath>",
  "operator" : {
     "service": "hostport"
   }
}
```

The URL can provide arguments:
- `keystore=<dir>` that specifies the location of the keystore
- `store=<dir>` that specifies a directory that contains the named operator
- `[user|account|operator]Key` - includes the public key for user, account, operator,  If no prefix (user/account/operator is provided, it targets the last object in the configuration path)
- `[user|account|operator]Seed=<optional public key>` - include the seed for user, account, operator, if an argument is provided, the seed for the specified public key is provided - this allows targeting a signing key. If no prefix (user/account/operator is provided, it targets the last object in the configuration path)
- `[user|account|operator]Name` - includes the friendly name for the for user, account, operator,  If no prefix (user/account/operator is provided, it targets the last object in the configuration path)

`nsc://operator/account/user?seed`:
```json
{
  "operator": { "service": "host:port" },
  "user": {
    "seed": "SUXXXXXXXXX"
  }
}
```

NSC will offer an interface where it can request it as API, but will also allow you to do: `nsc generate profile <URL>` and spew the JSON out which can be redirected using `--out-file`.

**Comment by ripienaar** [comment]
looks good - exit 1 on 404

**Comment by ripienaar** [comment]
@aricart do you know when this will see a release?

**Comment by aricart** [comment]
@ripienaar just did  - see https://github.com/nats-io/nsc/releases/tag/0.5.0

**Comment by ripienaar** [comment]
Thanks, added to `nats` :)

**Comment by aricart** [comment]
it is intended for nats cli and is used internally by it. - but with that said, really it could be public

**Comment by aricart** [comment]
@brianmcgee https://github.com/nats-io/nsc/pull/603
