### ISSUE TITLE
Is there a `nsc` go client ?

### ISSUE THREAD

**Issue by masudur-rahman** [nats-io/nsc#288]
I was wondering if I could use `nsc` from my `Go` app. I wanted to import a package which can do everything that `nsc` CLI tool can do.

Is there a go client available for this ?

**Comment by matthiashanel** [comment]
The "client" would be the jwt library itself https://github.com/nats-io/jwt as well as the nkey https://github.com/nats-io/jwt library.
They have create/new functions for operator/accounts/user. You set the claim fields you want set + encode.
Does this work for you?

**Comment by masudur-rahman** [comment]
I think [nats-io/jwt](https://github.com/nats-io/jwt) will do the work.

Thanks @matthiashanel .

**Comment by MichaelVoelkel** [comment]
But is that only part of it? What about nsc push, nsc describe, nsc export, other nsc adds like imports/exports...? All in there? Example page doesn't look like it
