### ISSUE TITLE
Allow revoking users that are not in the nkey store

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nsc#302]
Currently `nsc` prevents revoking a user that is not present in the filesystem

```sh
nsc revocations delete_user -a KUBECON -n UBS7HNAO2NPNLT...
Error: user UBS7HNAO2NPNLT3DFXH2ABAJT55N2AF67UANPL7S7AFNKYMNSMBTZDMX does not exist in the current account
```

**Comment by wallyqs** [comment]
This is to support use case of revoking in this tutorial: https://github.com/wallyqs/kubecon2020

**Comment by matthiashanel** [comment]
@aricart would you be preferring a new option -public-user-key <> or allow for -n to be used directly if the value can be interpreted as public user nkey?

**Comment by aricart** [comment]
I think we can just take the public key for the user
