### ISSUE TITLE
Get event when account created

### ISSUE THREAD

**Issue by gedw99** [nats-io/nsc#353]
Is it possible to get an event on the NAtS stream when an account mutation happens ?

if not then we will have to wrap nats account creation so we can publish a mutation event onto NATS itself.

the intent is because in a large system you need to tell other systems about account mutations

**Comment by aricart** [comment]
Actually this already exists - whenever nsc pushes an account to the resolver or an nats-account-server there will be an event like this published from within the system account, the payload contains the account JWT (new or update)
```
"$SYS.REQ.CLAIMS.UPDATE" with reply "_INBOX.yNUs6XzQ4RtcvziWRV5qty"
eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJDS0tJVVIzUUlZT0U1VklOVDZMMzJFTDRLWEFZTlFFQzc0TkNMVjMyUkZXQk40TFNFUFlRIiwiaWF0IjoxNjc3NTE2MTI4LCJpc3MiOiJPRDRIRTZCRFFCMkZQTEVBWFRTNFU0NFBBTlpPREFKUEJRQUlGQTJFUlRNNDVBTkRUS0tYQktSRSIsIm5hbWUiOiJBIiwic3ViIjoiQUREMlYzU0JPNVRXUEpPT1BLWTZYN0xNM1dIV0NEQkI1SVdJNk5QSkpUTlI3SldRTUxZRFYyWk8iLCJuYXRzIjp7ImxpbWl0cyI6eyJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsIndpbGRjYXJkcyI6dHJ1ZSwiY29ubiI6LTEsImxlYWYiOi0xfSwiZGVmYXVsdF9wZXJtaXNzaW9ucyI6eyJwdWIiOnt9LCJzdWIiOnt9fSwiYXV0aG9yaXphdGlvbiI6eyJhdXRoX3VzZXJzIjpudWxsfSwidHlwZSI6ImFjY291bnQiLCJ2ZXJzaW9uIjoyfX0.ItuJBsyiTS78E0rJH1ZbN9PqM_yeYeUaSAe3MfgREzvR9BbQdvm2CGvVd_uPhx07iAKmVPCCcdMlQ0ZjDXZOAg
```

if you are listening to this, never reply as this how the internals knows if the JWT was distributed - so simply listen on the publishes.
