### ISSUE TITLE
Revocations are slow with a large amount of users in the datastore

### ISSUE THREAD

**Issue by rayjanoka** [nats-io/nsc#423]
I'm not sure how big of an issue this is, but I noticed that revocations become significantly slower as users are added to the datastore.

I generated 10k JWT users and imported them and my revocation takes 2 full seconds:
```shell
➜ nsc list users -a game 2>&1 | wc -l
10000

➜ time nsc revocations add-user -a game -n UDZN6TS65YFNUDSD462UMWL5IACMSJP2IITEEQJTYRSZMC4AGNSQX5ZG
[ OK ] revoked user "UDZN6TS65YFNUDSD462UMWL5IACMSJP2IITEEQJTYRSZMC4AGNSQX5ZG"

________________________________________________________
Executed in    2.02 secs    fish           external
   usr time    1.99 secs    1.17 millis    1.99 secs
   sys time    0.14 secs    0.00 millis    0.14 secs
```

With a single user in the datastore it is fast 30 milliseconds:
```shell
➜ nsc list users -a game 2>&1 | wc -l
1

➜ time nsc revocations add-user -a game -n UDSAR4URREWCO54OBKMXMYRBXU7JJEYRGHY7QYCWAI3M4FCXAB7WGTQR
[ OK ] revoked user "UDSAR4URREWCO54OBKMXMYRBXU7JJEYRGHY7QYCWAI3M4FCXAB7WGTQR"

________________________________________________________
Executed in   30.96 millis    fish           external
   usr time   19.47 millis    1.48 millis   17.99 millis
   sys time   13.49 millis    0.00 millis   13.49 millis
```

**Comment by aricart** [comment]
If you are managing 10K users on a single account, possibly that is never going to scale well. Assuming you have users that pay for your service, I would instead consider generating an account per customer, and then creating a user for that account. If the billing or some other event determines whether the user is valid or not, I would instead update the account and drop all the limits on it. When the user connects to the server, and the account is fetch, if the billing is not current or they have exceeded game time limits, etc, the dropped limits on the account will make them disconnect.

Also if you are using `nsc` to perform all these operations, you might want to start thinking about using the JWT library directly.
