### ISSUE TITLE
Provide a utility to bundle credentials for transfer between machines

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nsc#428]
From an email chain with a user:

```text
"copying working credentials sanely between machines"
is a use-case which some folks are actively working on
improving right now...

Oh wow, this would be really helpful. This is currently really complicated and error-prone.
```

One option might be a way to tar/zip all or a subset of credentials and then untar/unzip onto the target machine in the correct location. A really nice to have would be encrypting and decrypting the tarball/zip.

**Comment by aricart** [comment]
@ColinSullivan1 how are they currently handling credential generation?
`nsc generate -a A -u U -o /some/file/path` is the right workflow.

Bulk copying credentials in a tar ball means that the user wants all the credentials (so can possibly have a bigger blast radius than expected). For that use case, they can just grab the credentials from `${NKEYS_PATH}/creds/<operator>/<account>`

**Comment by aricart** [comment]
As for transferring/encrypting workflow, there are better tools such as ansible, etc to provision a machine, while using some mechanism for storing. For encrypting, the most secure mechanism is for the client to provide a user public key, and have the account 'manager' generate an user JWT for that user, this way the secret never leaves it's owner.

**Comment by ColinSullivan1** [comment]
I didn't share enough about the use case - sorry about that.  The higher level use case is transferring private credentials from machine to machine for use with `nsc`.  I think a utility to do this would be less error prone than copying directories or regenerating user credentials.  Could see a case for wanting to copy all credentials, specific operator, accounts, or even users.  In this case, the user didn't know to copy the operator jwt/creds resulting in `nsc` not working on the target machine.  We haven't documented a process to do this, and creating a utility to do this would help users do this and allow for directory structure / file changes in the future without impacting users.

The original question:
```
What is the correct procedure to share those credentials with my team, i.e. how to I import those into nsc on a different computer? ```

**Comment by aricart** [comment]
Added `--include-jwt` to the keys export - this puts all the keys and their associated JWTs in a directory. The jwts are named after the identity - as this insures uniqueness - creating an environment with `nsc fix --in dir...` which would on-board all the assets into a keystore/etc creating a clean env with just these assets.
