### ISSUE TITLE
Unable to allow User pub/sub to $JS.API.STREAM.INFO.*

### ISSUE THREAD

**Issue by DustinReagan** [nats-io/nsc#450]
I have a User that needs to be able to query and create Jetstream keyvalue stores.  I attempted to add pub/sub access to $JS.API.STREAM.INFO.* in order to give the User the ability to query and create keyvalue stores:

```
96f4d12cdd02:~# nsc edit user RequestCacheService --allow-pubsub "$JS.API.STREAM.INFO.*"
[ OK ] added pub pub ".API.STREAM.INFO.*"
[ OK ] added sub ".API.STREAM.INFO.*"
[ OK ] generated user creds file `/nsc/nkeys/creds/LegacyBank/LegacyBank/RequestCacheService.creds`
[ OK ] edited user "RequestCacheService"
```

As you can see above, pub sub was added for ".API.STREAM.INFO.*", not "$JS.API.STREAM.INFO.*".

How do I allow a User permissions to query & create Jetstream keyvalue stores?

**Comment by aricart** [comment]
The reason why is the shell intercepted "$JS" and tried to substitute it with an environment variable. You need to escape your input. You can try:

`nsc add user U --allow-pubsub '$JS.API.STREAM.INFO.*'
