### ISSUE TITLE
flags for users differ

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nsc#46]
I find some commands want -n for name and some want -u for user, but both mean same thing. Be good to be consistent.

**Comment by aricart** [comment]
the issue is `describe` vs `add` - will fix via #47
the various describe commands can take optional arguments for specifying the account and the name

**Comment by aricart** [comment]
These already work correclty.
nsc add user --name  X
nsc describe user --name X
nsc edit user --name X

Fixed nsc generate creds.

**Comment by aricart** [comment]
--name always refers to the object of the verb. I am not seeing any discrepancies with nsc test flags > flags.csv
