### ISSUE TITLE
Outdated `nsc` documentation at `https://nats-io.github.io/nsc/`

### ISSUE THREAD

**Issue by mprimi** [nats-io/nsc#465]
Searching for `nats nsc`, a very prominent result on both Google and DDG is: https://nats-io.github.io/nsc/

However this manual pages looks outdated (~1 year old):

```
Auto generated by spf13/cobra on 18-Mar-2021
```

Maybe the process that was supposed to auto-generate this pages is broken?

**Comment by aricart** [comment]
@mprimi yikes - thank you for pointing this out.
