### ISSUE TITLE
`nsc push` ignores Operator's service URLs

### ISSUE THREAD

**Issue by mprimi** [nats-io/nsc#466]
According to documentation[1][2] `nsc push` uses the operator's 'service-url' field to decide where to push.

(The **optional** `-u`/`--account-jwt-server-url` option is provided to override the operator URLs)

In practice, looks like operator's 'service URL' is **ignored** by `nsc push`.
And the `-u` option is effectively required.

Example / repro:

### 1. Create Operator/Account/User:
```
$ nsc add operator MyOperator
$ nsc add account MyAccount
```

### 2. Try to push
```
$ nsc push --account MyAccount
Error: no account server url or nats-server url was provided by the operator jwt
```

Fair enough! The operator doesn't have a service-url set!

### 3. Set service-url and retry
```
$ nsc edit operator --service-url nats://localhost:4222

$ nsc describe operator MyOperator
+----------------------------------------------------------------------------------+
|                                 Operator Details                                 |
+-----------------------+----------------------------------------------------------+
| Name                  | MyOperator                                               |
[...]
| Operator Service URLs | nats://localhost:4222                                    |
[...]
+-----------------------+----------------------------------------------------------+
```

How about now?

```
$ nsc push --account MyAccount
Error: no account server url or nats-server url was provided by the operator jwt
```

### Workaround

End result: the `-u` option seems to be **required**.

```
$ nsc push --account MyAccount -u nats://127.0.0.1:4222
```

The operator's 'server-url' field seems to be ignored.

If requiring `-u` is not the intended behavior, then this may be a bug: **the operator's service-url is not being taken into account**. 

Also, the error message implies there's a way to set 'service-url for an account', but I found no such option. Maybe the message is deprecated?

 > Error: no account server url (...) was provided by the operator jwt

[1] https://docs.nats.io/using-nats/nats-tools/nsc/basics#creating-an-operator-account-and-user
[2] `nsc push -h`

**Comment by mprimi** [comment]
Update: found how to set `service-url` for an account:

`nsc edit operator -u <url>`

**Comment by aricart** [comment]
for pushing, it is not `--service-url`, but rather `--account-jwt-server-url`. Service is where nats clients connect, account server is for pushing configurations to an account server

**Comment by mprimi** [comment]
In retrospect, this all makes sense, sorry for the false alarm.

The thing that confused me (and possibly others similarly) is here: https://docs.nats.io/using-nats/nats-tools/nsc/basics

The `--service-url` option for operator is shown in that example, but it's not necessary for the following examples, or explained in detail.
