### ISSUE TITLE
describe should use last param as name

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nsc#47]
This should work. 

```nsc describe user test_system
Error: accepts at most 0 arg(s), received 1
```

Should not have to put -u, or -a or -n before last arg.

**Comment by sasbury** [comment]
i have seen this in the debugger, when i am running a command with 0 args, not sure how it is related.

**Comment by aricart** [comment]
the commands that don't have additional verbs/nouns will print this.

**Comment by aricart** [comment]
https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46 calls it right.
I think the goal should be:

- interactive when you do `nsc add user` - with no flags or options
- if name is required, we can do the -n or an additional argument,
- if flags are provided, the command works or fails, it doesn't jump into interactive

**Comment by derekcollison** [comment]
So you are stating the case that `nsc describe account alberto` should fail as above with the cryptic message or saying it should work?

**Comment by derekcollison** [comment]
`heroku create [APP]` seems to argue for my point that `nsc escribe account [ACC]` should work.

**Comment by aricart** [comment]
I think we should adopt the basic name. - The error is because the library is saying the command was invoked with arguments, but it takes none (it takes flags).

**Comment by aricart** [comment]
The heroku doc is also inconsistent in this area, they say you should use flags. I think the correct thing to do is to take the name (and the flag). But if flags are provided, it doesn't do any interactive, it just tries to do what you ask/default the rest and done. So under that roof, that means:

- `nsc add user alberto` won't prompt for anything.
- `nsc add user` would go into interactive

**Comment by derekcollison** [comment]
Sounds good to me.

**Comment by aricart** [comment]
So this issue combines the need to not have to provide the name flag for the object in question, and the need to run in interactive mode without the -i flag. For the -i flag, we have #143.
