### ISSUE TITLE
nsc load doesn't behave correctly if there are other operators installed

### ISSUE THREAD

**Issue by aricart** [nats-io/nsc#474]
synadia@malaga ~/.l/s/n/nsc [1]> set -x NSC_LOCAL_OPERATOR http://localhost:9090/jwt/v1/operator
synadia@malaga ~/.l/s/n/nsc [1]> nsc load --profile "nsc://LOCAL?secret=SAAHUR5MSQMEBFY5LDZMWLALPERA2W2RA3NL6MJ5MVDAT23Q6KEIB74BKI"
Error: nsc invoke failed: exit status 1

**Comment by wallyqs** [comment]
Could reproduce btw, seems to failing to store the context with the config somehow now.

**Comment by aricart** [comment]
I thought we had seen it do that, but then I tried it and it worked, maybe I had the operator etc on - wondering if you can just try with the cluster that Caleb has.
