### ISSUE TITLE
nsc load --profile & env variable issues

### ISSUE THREAD

**Issue by philpennock** [nats-io/nsc#478]
I used a web app which provided me with an `nsc load --profile` command to invoke; the app gave the `synadia` operator name in the nsc URN, although it was actually for a synadia-test stack.

When trying to use that:
1. Unless `nsc env -o foo` is used to set an operator name, `Error: set an operator -- 'nsc env -o operatorName'`
2. After setting the operator to an existing operator, where the operator JWT is on disk and contains an `account_server_url` field, that is not used and I still have to set an environment variable anyway
3. There's no handling of a hyphen in an operator name and the env var needs to be all upper-cased, so I had to switch `synadia-test` to `synadia_test`, and adjust the URL
4. With `nsc://synadia_test?` in the profile URN and `$NSC_SYNADIA_TEST_OPERATOR` in environment, but the `nsc env -o` value unchanged, the `nsc load --profile` invocation fails with an unhelpful `Error: nsc invoke failed: exit status 1`
5. After using `nsc env -o synadia_test` and repeating, everything worked.

**Comment by aricart** [comment]
@wallyqs any progress on this

**Comment by wallyqs** [comment]
chasing a bug that happens when jumping from context to context on the same run but wip branch here, at least invoke errors gone now https://github.com/nats-io/nsc/tree/nsc-load-natscontext
