### ISSUE TITLE
on an reset nsc environment, `nsc invoke failed` when doing a load

### ISSUE THREAD

**Issue by aricart** [nats-io/nsc#482]
bash-3.2$ export nsc_O_operator=https://nas.nas-dev.synadia.io/jwt/v1/operator
bash-3.2$ nsc load --profile "nsc://O?secret=SAAPZ7XT3T4QPUSFYJQ5SIMKTAEK6AZ5MMGKQ7KADYBNMNJFNB2WJGCBXA"
Error: nsc invoke failed: exit status 1
Usage:
  nsc load [flags]

Flags:
  -h, --help             help for load
      --profile string   Profile URL to initialize NSC and NATS CLI env
      --seed string      Seed of the account used to create users
      --url string       URL of the account server
      --user string      Default username (default "default")

Global Flags:
      --config-dir string     nsc config directory
      --data-dir string       nsc data store directory
  -i, --interactive           ask questions for various settings
      --keystore-dir string   nsc keystore directory
  -K, --private-key string    Key used to sign. Can be specified as role (where applicable),
                              public key (private portion is retrieved)
                              or file path to a private key or private key

bash-3.2$

**Comment by wallyqs** [comment]
Fixed via #483
