### ISSUE TITLE
Automatisation / bootstrapping / API

### ISSUE THREAD

**Issue by MichaelVoelkel** [nats-io/nsc#497]
Hi,

I would like to set up a nice NATS environment but I would like to do so in an automatised way with some bootstrap scripts.

The approach that currently seems best is to write some scripts that use `nsc` via shell and parse the output. This is somewhat okay for `describe` because of the `-J` option but painful for many other commands like `add` and the like.

Sadly, the `nsc` Go API is in the `internal` folder, so use is not encouraged.

What would you guys say is the best way?

**Comment by aricart** [comment]
have you looked at `nsc generate config` command.

If you are using a mem-resolver, you can do:
`nsc generate config --mem-resolver --sys-account SYS --config-file /tmp/mem.conf`

If you are using a nats-resolver:
`nsc generate config --nats-resolver --sys-account SYS --config-file /tmp/resolver.conf`

**Comment by MichaelVoelkel** [comment]
In how far is an existing config important/detrimental then? And it seems, `nsc init` is needed before?

I use the official NATS docker container, but `nsc push` fails with:

```
[ERR ] push to nats-server "nats://localhost:4222" using system account "SYS":
       [ERR ] push root to nats-server with nats account resolver:
              [ERR ] failed to get response to push account: nats: no responders available for request
```
Port 4222 is open, though (checked with `nc`)... Seems like the generate config commands are just part of the puzzle?

**Comment by aricart** [comment]
What is your server configuration? No responders means that there's no service listening for that update (the request published, didn't have something listening on it). 

Can you put the steps you are doing from running server to nsc command?

**Comment by MichaelVoelkel** [comment]
Okay, it seems to work like this! Nice, thank you!

So, it seems these are the complete steps for some bootstrapping:
```
nsc init -n operator-name
nsc generate config --nats-resolver --sys-account SYS --config-file resolver.conf
docker run -d -v resolver.conf:/resolver.conf --name nats -p 4222:4222 --restart unless-stopped -ti nats:latest -c /resolver.conf
nsc edit operator -u nats://localhost:4222
```
Nice!

Okay and here I probably also do not need more feedback.

Hm, the only slightly uncomfortable thing is that if I add a new user via nsc automatically, I need to parse the output for the stuff between the two backticks...
```
[ OK ] generated and stored user key "UDPRORZJXYZLLQ5A5IMEPFO66FUTUQOJCVV74EUIM4WQOQOUBBW7XI77"
[ OK ] generated user creds file `~/.local/share/nats/nsc/keys/creds/operator/react/hi.creds`
[ OK ] added user "hi" to account "react"
```

But reading the creds file in this way is probably the best way to automatise things then, right? (I know, stretching the ticket a bit, but your input is really helpful)

**Comment by MichaelVoelkel** [comment]
Okay, having dokerized all of this, I have some nice file that sets everything up. However, the last unclarity to me is: How can I pull all this configuration from the server? If I use `nsc pull -A` it tells me `Authorisation violation` or even that my config dirs do not exist... But I mean, I would like to clone what is on the server, what is the quickest way here?

**Comment by aricart** [comment]
@MichaelVoelkel I think you might be missing a SYS account setting on the operator.

```bash
synadia@malaga /tmp> nsc add operator O
[ OK ] generated and stored operator key "OAC7VPSVQPRHMJCHFXRO267B4J7XT76MDIRWEUG3AFG3WZTXTCNCJMQU"
[ OK ] added operator "O"
[ OK ] When running your own nats-server, make sure they run at least version 2.2.0
synadia@malaga /tmp> nsc add account SYS
[ OK ] generated and stored account key "ABT32ZXO635EKGOEQCVVKWFZ6FESGZIOTFVPVR6B3CPUXGHDXQ774U5M"
[ OK ] added account "SYS"
synadia@malaga /tmp> nsc edit operator --system-account ABT32ZXO635EKGOEQCVVKWFZ6FESGZIOTFVPVR6B3CPUXGHDXQ774U5M --account-jwt-server-url nats://localhost:4222 --service-url nats://localhost:4222
[ OK ] set account jwt server url to "nats://localhost:4222"
[ OK ] set system account "ABT32ZXO635EKGOEQCVVKWFZ6FESGZIOTFVPVR6B3CPUXGHDXQ774U5M"
[ OK ] added service url "nats://localhost:4222"
[ OK ] edited operator "O"
synadia@malaga /tmp> nsc generate config --sys-account SYS --nats-resolver --config-file /tmp/resolver.conf
[ OK ] wrote server configuration to `/tmp/resolver.conf`
Success!! - generated `/tmp/resolver.conf`
synadia@malaga /tmp> nats-server -c resolver.conf &
[13924] 2022/05/10 17:01:26.592481 [INF] Starting nats-server
[13924] 2022/05/10 17:01:26.592570 [INF]   Version:  2.8.2-beta.5
[13924] 2022/05/10 17:01:26.592572 [INF]   Git:      [not set]
[13924] 2022/05/10 17:01:26.592575 [INF]   Name:     NBOP5GWGLK6A4SQPYXYYAJSO3E4N256F432JQHQBIHYD4AHVC6WB6GCL
[13924] 2022/05/10 17:01:26.592576 [INF]   ID:       NBOP5GWGLK6A4SQPYXYYAJSO3E4N256F432JQHQBIHYD4AHVC6WB6GCL
[13924] 2022/05/10 17:01:26.592591 [INF] Using configuration file: resolver.conf
[13924] 2022/05/10 17:01:26.592593 [INF] Trusted Operators
[13924] 2022/05/10 17:01:26.592596 [INF]   System  : ""
[13924] 2022/05/10 17:01:26.592598 [INF]   Operator: "O"
[13924] 2022/05/10 17:01:26.592616 [INF]   Issued  : 2022-05-10 17:01:08 -0500 CDT
[13924] 2022/05/10 17:01:26.592619 [INF]   Expires : 1969-12-31 18:00:00 -0600 CST
[13924] 2022/05/10 17:01:26.593160 [INF] Managing all jwt in exclusive directory /tmp/jwt
[13924] 2022/05/10 17:01:26.593356 [INF] Listening for client connections on 0.0.0.0:4222
[13924] 2022/05/10 17:01:26.593604 [INF] Server is ready
synadia@malaga /tmp> nsc add account A
[ OK ] generated and stored account key "ADX4PDYIEJ3QYN6KRCCY6SDDGOLMYF24THHG47CNSLKWUC5DURIJ776F"
[ OK ] added account "A"
synadia@malaga /tmp> nsc pull -A
[ OK ] pulled "SYS" from the account server:
       [ OK ] stored account "SYS"
synadia@malaga /tmp> nsc pull -a ADX4PDYIEJ3QYN6KRCCY6SDDGOLMYF24THHG47CNSLKWUC5DURIJ776F
Error: "ADX4PDYIEJ3QYN6KRCCY6SDDGOLMYF24THHG47CNSLKWUC5DURIJ776F" not in accounts for operator "O" in `/tmp/stores`
Usage:
  nsc pull [flags]

Flags:
  -a, --account string          account name
  -A, --all                     operator and all accounts under the operator
  -h, --help                    help for pull
  -F, --overwrite-newer         overwrite local JWTs that are newer than remote
      --system-account string   System account for use with nats-resolver enabled nats-server. (Default is system account specified by operator)
      --system-user string      System account user for use with nats-resolver enabled nats-server. (Default to temporarily generated user)

Global Flags:
      --config-dir string     nsc config directory
      --data-dir string       nsc data store directory
  -i, --interactive           ask questions for various settings
      --keystore-dir string   nsc keystore directory
  -K, --private-key string    Key used to sign. Can be specified as role (where applicable),
                              public key (private portion is retrieved)
                              or file path to a private key or private key

synadia@malaga /tmp [1]> nsc push -a A
[ OK ] push to nats-server "nats://localhost:4222" using system account "SYS":
       [ OK ] push A to nats-server with nats account resolver:
              [ OK ] pushed "A" to nats-server NBOP5GWGLK6A4SQPYXYYAJSO3E4N256F432JQHQBIHYD4AHVC6WB6GCL: jwt updated
              [ OK ] pushed to a total of 1 nats-server
synadia@malaga /tmp> nsc pull -A
[ OK ] pulled "A" from the account server:
       [ OK ] stored account "SYS"
       [ OK ] stored account "A"
synadia@malaga /tmp> nsc add account B
[ OK ] generated and stored account key "ABYMSS3FM2SK2SNHQTSHDZSWHTXGJ6HKDCAAZXOKZZPI6NQHMCCAJNPC"
[ OK ] added account "B"
synadia@malaga /tmp> nsc push -A
[ OK ] push to nats-server "nats://localhost:4222" using system account "SYS":
       [ OK ] push A to nats-server with nats account resolver:
              [ OK ] pushed "A" to nats-server NBOP5GWGLK6A4SQPYXYYAJSO3E4N256F432JQHQBIHYD4AHVC6WB6GCL: jwt updated
              [ OK ] pushed to a total of 1 nats-server
       [ OK ] push B to nats-server with nats account resolver:
              [ OK ] pushed "B" to nats-server NBOP5GWGLK6A4SQPYXYYAJSO3E4N256F432JQHQBIHYD4AHVC6WB6GCL: jwt updated
              [ OK ] pushed to a total of 1 nats-server
       [ OK ] push SYS to nats-server with nats account resolver:
              [ OK ] pushed "SYS" to nats-server NBOP5GWGLK6A4SQPYXYYAJSO3E4N256F432JQHQBIHYD4AHVC6WB6GCL: jwt updated
              [ OK ] pushed to a total of 1 nats-server
synadia@malaga /tmp> nsc pull -A
[ OK ] pulled "A" from the account server:
       [ OK ] stored account "SYS"
       [ OK ] stored account "B"
       [ OK ] stored account "A"
```

**Comment by MichaelVoelkel** [comment]
Hm, I think, my problem is based on having two different hosts and I have a design problem here (potentially). Nats itself runs now in a container and therefore has it's own docker-internal user/config/creds directories.
However, it would be nice to manage with nsc accounts _outside_ of this docker container.
This basically means, I have two hosts and would like to manage/push accounts into the other host.

Maybe, this is tedious and I should have the directory with accounts shared across containers

**Comment by MichaelVoelkel** [comment]
So from docker I imported the key with `nsc import account --force --file host-account.jwt`, so `host-account.jwt` was created by the operator of the host (not from docker), which is why I need force.
Now, I hoped that I could still `push` from the host machine (not docker) via `push -a host-account` the account plus users, but nope, I get `authorization violation`... Any clue? I can hardly have the operator be duplicated on the host machine and the docker VM, I suppose... (or at least it feels less safe)

**Comment by aricart** [comment]
Too many issues at the same time, lets take them one by one:

- When using nsc under docker you have to map a local volume - this will give you a local backup etc.

- In a cluster, (which is what I am understanding you are doing) you need to have the *same operator and system account* for all members of the cluster. You can then create a shared config file that you can reuse in both containers, the containers will then map different service ports, on the host.

- In terms of safety, we have several (very long/detailed) documents you can read. But the TL;DR is that you use signing keys with the operators and you use those to issue the accounts. The delegated authentication model of JWT requires that the tree be known, so this means that the accounts are validated as being issued by the operator (or one of its signing keys). User connections are validated as being issued by a valid account.

- not quite sure what `describe --raw --output-file
> nsc describe account B --raw
eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJHNFhMUUEyUzVYNDc2QVI1SVNUQzJFWFdMWUoyVTdHUlZGRlg0VTdITlNRWFZYTENHSTJRIiwiaWF0IjoxNjUyMjIwMTM2LCJpc3MiOiJPQUM3VlBTVlFQUkhNSkNIRlhSTzI2N0I0SjdYVDc2TURJUldFVUczQUZHM1daVFhUQ05DSk1RVSIsIm5hbWUiOiJCIiwic3ViIjoiQUJZTVNTM0ZNMlNLMlNOSFFUU0hEWlNXSFRYR0o2SEtEQ0FBWlhPS1paUEk2TlFITUNDQUpOUEMiLCJuYXRzIjp7ImxpbWl0cyI6eyJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsIndpbGRjYXJkcyI6dHJ1ZSwiY29ubiI6LTEsImxlYWYiOi0xLCJoYV9yZXNvdXJjZXMiOjB9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJ0eXBlIjoiYWNjb3VudCIsInZlcnNpb24iOjJ9fQ.YaUSmrEJx8K2u9jzzzXIVOO6GRBfB-O5L80n-G-ObAWrWKUAPLCw2ofvRfO_bvYsuwSz0Q2XA53DnRbrHHg9BA
synadia@malaga /t/k/c/O/B> nsc describe account B --raw > /tmp/out.jwt
synadia@malaga /t/k/c/O/B> nsc describe jwt -f /tmp/out.jwt
+--------------------------------------------------------------------------------------+
|                                   Account Details                                    |
+---------------------------+----------------------------------------------------------+
| Name                      | B                                                        |
| Account ID                | ABYMSS3FM2SK2SNHQTSHDZSWHTXGJ6HKDCAAZXOKZZPI6NQHMCCAJNPC |
...

Also if I point `nsc describe jwt -f` to a creds file, it does the right thing. Is it possible that there's some version issue?

**Comment by MichaelVoelkel** [comment]
Thank you a lot for your detailed answer! This answers all of my questions so far, especially the one about clusters... It will be interesting to see how I should have SYS+operator the same for all cluster entities, but since I only have one node so far, I think, I will just share the config directories and might already be done. I will try this out.

For the `describe` command, I will probably better answer in the other ticket.

**Comment by aricart** [comment]
@MichaelVoelkel thanks for the question - it flushed a critter, for which I opened a PR already.
