### ISSUE TITLE
"--expiry" flag for account does not work well with fractional values

### ISSUE THREAD

**Issue by goku321** [nats-io/nsc#505]
See the attached screenshot below:

![Screenshot 2022-06-21 at 1 01 19 PM](https://user-images.githubusercontent.com/12848015/174743267-16ed9265-a378-4297-9b1d-65fa625039fb.png)

Proposal: It should at least throw an error and only accept integer values.

**Comment by aricart** [comment]
Agreed! - fixed by https://github.com/nats-io/nsc/pull/509
