### ISSUE TITLE
Follow Go module version numbering standards

### ISSUE THREAD

**Issue by qjcg** [nats-io/nsc#523]
Currently this repo does not follow [Go Module Version Numbering](https://go.dev/doc/modules/version-numbers) corresponding to the currently released version (2.x.x) (e.g. as done elsewhere with [nats-server](https://github.com/nats-io/nats-server/blob/main/go.mod#L1)).

Updating the importpath (e.g. via `go mod edit -module github.com/nats-io/nsc/v2`) would fix this.

**Comment by wallyqs** [comment]
We have retagged the repo and change import paths to support v2 so this is now suported:
```
go install github.com/nats-io/nsc/v2@latest
```
Fixed via #530

**Comment by qjcg** [comment]
@wallyqs Awesome news, thank you!
