### ISSUE TITLE
Plan to adopt Go module versioning

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nsc#530]
Currently the repo has been using non-standard git tags that are incompatible with Go module versioning (2.7.5 -> v2.7.5) so lookup functionality with Go modules is not optimal and also proxy.golang.org is having degraded performance lately (https://github.com/golang/go/issues/57185). 

Things to update/confirm to make the move:

- [x] Version to use: v2.7.6 based from `2.7.5` (https://github.com/nats-io/nsc/releases/tag/2.7.5)
- [x] self-update functionality (it would check latest from github)
- [x] installer updates, add `v` prefix (https://get-nats.io/install.sh)
- [x] nats-server docker nightly change to `go install github.com/nats-io/nsc/v2@latest` (https://github.com/nats-io/nats-server/blob/main/docker/Dockerfile.nightly#L12 || https://github.com/nats-io/nats-server/commit/74d9c515333e16942bf491f924e68d8f3a580e8d)
- [x] nats-box container, need to change to `go install github.com/nats-io/nsc/v2@latest` instead (https://github.com/nats-io/nats-box/blob/main/Dockerfile#L13 || https://github.com/nats-io/nats-box/commit/6d97b05e447ca521fadea026fd61c35f163b2cad || https://github.com/nats-io/nats-box/pull/45)
- [x] update internal paths into v2 paths to be like `github.com/nats-io/nsc/v2` (merged: https://github.com/nats-io/nsc/pull/532)
- [x] go releaser artifacts names (`nsc-darwin-arm64.zip` do not include version)
- [x] nsc version output: `nsc version 2.7.6`
- [x] homebrew, update to v2.7.6: (https://github.com/nats-io/homebrew-nats-tools/blob/master/Formula/nsc.rb#L8 || https://github.com/nats-io/homebrew-nats-tools/pull/12)

**Comment by philpennock** [comment]
The installer update _should_ just be to make sure that when `synadia-nats-channels.conf` is updated, the value of `VERSION_stable_nsc` should be given with a `v` prefix, just like the `nats` line one before it.  You can test with:

```sh
./install.sh -F synadia-nats-channels.conf
```

before committing the change.

**Comment by wallyqs** [comment]
```
$ nsc update
Downloading version: latest⠦ Successfully updated to version 2.7.6

Release Notes:

This the same release as `2.7.5` but it is updated to use Go modules versioning.
To install via Go tooling, now `/v2` path as to be specified:

```sh
go install github.com/nats-io/nsc/v2@latest
```

## Changelog
* 31b7fba Merge pull request #534 from nats-io/release/v2.7.6
* e0333d7 Update goreleaser version
* 45f67cc Switch module to v2 properly
```

**Comment by wallyqs** [comment]
Installer:

```
$ curl -fSs https://get-nats.io/install.sh | sh

$HOME/.local/bin/nsc --version
nsc version 2.7.6
```

**Comment by wallyqs** [comment]
All things have been merged, closing now
