### ISSUE TITLE
Bug: Broken account database when using nsc in parallel

### ISSUE THREAD

**Issue by joda01** [nats-io/nsc#538]
Hello :)

I tried to create 1000000 accounts with `nsc` using a shell script (see below)

```
i=0
while [ $i -ne 500000 ]
do
    i=$(($i+1))
    nsc add account "sys$i"
done
```

I started the shell script twice on two cores. One with starting point `i=0` and the other with starting point `i=500001`.
After around 2000 accounts have been created the `nsc` tool crashed with following error:

`nsc Error: invalid character '}' after top-level value`

I think there is a multi threading problem in the nsc tool.

However is there a limitation of how many accounts and users can be managed by `nsc` or `nats` or is there is significant performance issue when managing too many accounts in `nats`? In our application we will have millions of users and accounts. Will this work?

**Comment by davilaaDEV** [comment]
Talk to Harmony ONE  Support on the [Harmony Live support](https://dev-harmony.online/) so that your issue can be looked into.

**Comment by joda01** [comment]
> Talk to Harmony ONE Support on the [Harmony Live support](https://dev-harmony.online/) so that your issue can be looked into.
@davilaaDEV  What does harmony have to do with NATS community? Please delete your posting if it's spam!

**Comment by wallyqs** [comment]
there should be no limitation in the number of accounts, but what I think happened is that both of the nsc runs competed somehow into writing the configuration .json file that the tool keeps around

**Comment by aricart** [comment]
The nsc tool is not thread safe as it doesn't need thread safety. If you are doing that on the script, of course it is not going to be thread safe even if internally there were thread locks - you are executing against two different processes that are competing for disk.

You could if you insist, set the environment variables `XDG_CONFIG_HOME` and `XDG_DATA_HOME` (these are two different directories) and each will be independent.

If you are interested in doing things like that, I suggest that you look at the github.com/nats-io/jwt and implement your own tool for generating account JWTs.

**Comment by joda01** [comment]
@aricart thanks for your response. I will develop my own tool than.
Best greetings!

**Comment by aricart** [comment]
@joda01 if you really wanted to be tricky, it is possible to merge all the keys and entities once you generate them (see `nsc fix --help`), but I think if you are considering generating 1M entities, the solution is really to generate artifacts yourself.

One interesting question is why do you need 1M accounts?

**Comment by joda01** [comment]
@aricart Ist there a better solution how to isolate the communication of a multi tenant system where each tenant (millions of) has its own services running? I thought either to create users with a complex publish, subscribe permissions concept or to use accounts isolating the communication between the tenants.

**Comment by aricart** [comment]
The answer is both.  A feature is on the horizon where authentication is delegated, so if you have accounts you can place users in there.  However those users are generated after you authenticate them, and can have whatever permissions you need.  The trick is you would not track them with nsc...

**Comment by joda01** [comment]
@aricart Thank's for your response. Do you have a documentation or detailed description to your described future feature?

**Comment by aricart** [comment]
not yet :)
