### ISSUE TITLE
nsc edit is checking if JetStream is available

### ISSUE THREAD

**Issue by sty-holdings** [nats-io/nsc#569]
When you enter the following command:
`nsc edit account SYS -k OD.....2Y --tag A`
You will get the following error:
`Error: jetstream not available for system account`
<img width="781" alt="NSC-1" src="https://user-images.githubusercontent.com/111923061/222811949-7c3a00c4-eeb9-43d9-adc5-fc638744d9be.png">

**Comment by aricart** [comment]
nsc doesn't check for sys account, it is simply reporting an error received from the nats-server.
@kimjarvis can you include your server config please?

**Comment by kimjarvis** [comment]
```bash
root@instance:/# cat $HOME/server.config
include resolver.conf
http_port: 8222
log_file: /root/server.log
debug: True
trace: True
jetstream: enabled
root@instance:/# nsc edit account -n SYS --tag "System account, used by nsc push" -H $HOME/O
Error: jetstream not available for system account
```
